// Mocks generated by Mockito 5.4.6 from annotations
// in makanapa/test/features/basket/data/repositories/basket_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:makanapa/features/basket/data/data_source/basket_data_source.dart'
    as _i4;
import 'package:makanapa/features/basket/data/models/entity/basket_group_isar_model.dart'
    as _i8;
import 'package:makanapa/features/basket/data/models/entity/basket_item_isar_model.dart'
    as _i6;
import 'package:makanapa/features/basket/data/models/response/basket_dashboard_response.dart'
    as _i2;
import 'package:makanapa/features/basket/data/models/response/basket_summary_response.dart'
    as _i3;
import 'package:makanapa/features/recipe/domain/models/ingredient_enum.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBasketDashboardResponse_0 extends _i1.SmartFake
    implements _i2.BasketDashboardResponse {
  _FakeBasketDashboardResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBasketSummaryResponse_1 extends _i1.SmartFake
    implements _i3.BasketSummaryResponse {
  _FakeBasketSummaryResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BasketRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBasketRemoteDataSource extends _i1.Mock
    implements _i4.BasketRemoteDataSource {
  MockBasketRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.BasketDashboardResponse> getIngredientMainData() =>
      (super.noSuchMethod(
            Invocation.method(#getIngredientMainData, []),
            returnValue: _i5.Future<_i2.BasketDashboardResponse>.value(
              _FakeBasketDashboardResponse_0(
                this,
                Invocation.method(#getIngredientMainData, []),
              ),
            ),
          )
          as _i5.Future<_i2.BasketDashboardResponse>);

  @override
  _i5.Future<_i3.BasketSummaryResponse> getIngredientByGroupId(int? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getIngredientByGroupId, [groupId]),
            returnValue: _i5.Future<_i3.BasketSummaryResponse>.value(
              _FakeBasketSummaryResponse_1(
                this,
                Invocation.method(#getIngredientByGroupId, [groupId]),
              ),
            ),
          )
          as _i5.Future<_i3.BasketSummaryResponse>);
}

/// A class which mocks [BasketLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBasketLocalDataSource extends _i1.Mock
    implements _i4.BasketLocalDataSource {
  MockBasketLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> cacheIngredientMainData(
    _i2.BasketDashboardResponse? response,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheIngredientMainData, [response]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cacheIngredientGroupData(
    _i3.BasketSummaryResponse? response,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheIngredientGroupData, [response]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<List<_i6.BasketItemEntity>> getBasketStream({
    required int? groupId,
    _i7.IngredientEnum? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBasketStream, [], {
              #groupId: groupId,
              #type: type,
            }),
            returnValue: _i5.Stream<List<_i6.BasketItemEntity>>.empty(),
          )
          as _i5.Stream<List<_i6.BasketItemEntity>>);

  @override
  _i5.Stream<_i8.BasketGroupEntity?> getIngredientsDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#getIngredientsDashboard, []),
            returnValue: _i5.Stream<_i8.BasketGroupEntity?>.empty(),
          )
          as _i5.Stream<_i8.BasketGroupEntity?>);

  @override
  _i5.Future<void> markIngredients(
    int? groupId,
    int? ingredientId,
    bool? isMarked,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markIngredients, [
              groupId,
              ingredientId,
              isMarked,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
