// Mocks generated by Mockito 5.4.6 from annotations
// in makanapa/test/features/home/presentation/create/controllers/create_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:makanapa/features/home/domain/models/create_plan_request.dart'
    as _i6;
import 'package:makanapa/features/home/domain/models/dashboard.dart' as _i7;
import 'package:makanapa/features/home/domain/models/weekly_plan.dart' as _i8;
import 'package:makanapa/features/home/domain/repositories/meal_plan_repository.dart'
    as _i4;
import 'package:makanapa/features/recipe/domain/models/class_enum.dart' as _i11;
import 'package:makanapa/features/recipe/domain/models/dish_enum.dart' as _i10;
import 'package:makanapa/features/recipe/domain/models/recipe_item.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RecipeItemCopyWith_1<$Res> extends _i1.SmartFake
    implements _i3.$RecipeItemCopyWith<$Res> {
  _Fake$RecipeItemCopyWith_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MealPlanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealPlanRepository extends _i1.Mock
    implements _i4.MealPlanRepository {
  MockMealPlanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<String, void>> getDashboardData() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardData, []),
            returnValue: _i5.Future<_i2.Either<String, void>>.value(
              _FakeEither_0<String, void>(
                this,
                Invocation.method(#getDashboardData, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<String, void>>);

  @override
  _i5.Future<_i2.Either<String, void>> reloadPlanDetail(int? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#reloadPlanDetail, [groupId]),
            returnValue: _i5.Future<_i2.Either<String, void>>.value(
              _FakeEither_0<String, void>(
                this,
                Invocation.method(#reloadPlanDetail, [groupId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<String, void>>);

  @override
  _i5.Future<_i2.Either<String, void>> createMealPlan(
    _i6.CreatePlanRequest? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMealPlan, [params]),
            returnValue: _i5.Future<_i2.Either<String, void>>.value(
              _FakeEither_0<String, void>(
                this,
                Invocation.method(#createMealPlan, [params]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<String, void>>);

  @override
  _i5.Stream<_i7.Dashboard?> getDashboardStream() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardStream, []),
            returnValue: _i5.Stream<_i7.Dashboard?>.empty(),
          )
          as _i5.Stream<_i7.Dashboard?>);

  @override
  _i5.Stream<_i8.WeeklyPlan?> getWeeklyPlanStream(int? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklyPlanStream, [groupId]),
            returnValue: _i5.Stream<_i8.WeeklyPlan?>.empty(),
          )
          as _i5.Stream<_i8.WeeklyPlan?>);
}

/// A class which mocks [RecipeItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeItem extends _i1.Mock implements _i3.RecipeItem {
  MockRecipeItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  String get enName =>
      (super.noSuchMethod(
            Invocation.getter(#enName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#enName),
            ),
          )
          as String);

  @override
  String get picture =>
      (super.noSuchMethod(
            Invocation.getter(#picture),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#picture),
            ),
          )
          as String);

  @override
  _i10.DishEnum get dishType =>
      (super.noSuchMethod(
            Invocation.getter(#dishType),
            returnValue: _i10.DishEnum.main,
          )
          as _i10.DishEnum);

  @override
  _i11.ClassEnum get classType =>
      (super.noSuchMethod(
            Invocation.getter(#classType),
            returnValue: _i11.ClassEnum.all,
          )
          as _i11.ClassEnum);

  @override
  String get urlLinks =>
      (super.noSuchMethod(
            Invocation.getter(#urlLinks),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#urlLinks),
            ),
          )
          as String);

  @override
  _i3.$RecipeItemCopyWith<_i3.RecipeItem> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$RecipeItemCopyWith_1<_i3.RecipeItem>(
              this,
              Invocation.getter(#copyWith),
            ),
          )
          as _i3.$RecipeItemCopyWith<_i3.RecipeItem>);
}
