// Mocks generated by Mockito 5.4.6 from annotations
// in makanapa/test/features/home/data/repositories/meal_plan_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:makanapa/features/home/data/data_source/plan_data_source.dart'
    as _i5;
import 'package:makanapa/features/home/data/models/entity/dashboard_isar_model.dart'
    as _i9;
import 'package:makanapa/features/home/data/models/entity/weekly_detail_isar_model.dart'
    as _i10;
import 'package:makanapa/features/home/data/models/response/create_plan_response.dart'
    as _i4;
import 'package:makanapa/features/home/data/models/response/dashboard/dashboard_response.dart'
    as _i2;
import 'package:makanapa/features/home/data/models/response/dashboard/weekly_plan_response.dart'
    as _i3;
import 'package:makanapa/features/home/domain/models/create_plan_request.dart'
    as _i7;
import 'package:makanapa/features/home/domain/models/weekly_plan.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDashboardResponse_0 extends _i1.SmartFake
    implements _i2.DashboardResponse {
  _FakeDashboardResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWeeklyPlanResponse_1 extends _i1.SmartFake
    implements _i3.WeeklyPlanResponse {
  _FakeWeeklyPlanResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreatePlanResponse_2 extends _i1.SmartFake
    implements _i4.CreatePlanResponse {
  _FakeCreatePlanResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlanRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlanRemoteDataSource extends _i1.Mock
    implements _i5.PlanRemoteDataSource {
  MockPlanRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.DashboardResponse> getDashboardData() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardData, []),
            returnValue: _i6.Future<_i2.DashboardResponse>.value(
              _FakeDashboardResponse_0(
                this,
                Invocation.method(#getDashboardData, []),
              ),
            ),
          )
          as _i6.Future<_i2.DashboardResponse>);

  @override
  _i6.Future<_i3.WeeklyPlanResponse> getWeeklyPlan(int? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklyPlan, [groupId]),
            returnValue: _i6.Future<_i3.WeeklyPlanResponse>.value(
              _FakeWeeklyPlanResponse_1(
                this,
                Invocation.method(#getWeeklyPlan, [groupId]),
              ),
            ),
          )
          as _i6.Future<_i3.WeeklyPlanResponse>);

  @override
  _i6.Future<_i4.CreatePlanResponse> createMealPlan(
    _i7.CreatePlanRequest? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMealPlan, [params]),
            returnValue: _i6.Future<_i4.CreatePlanResponse>.value(
              _FakeCreatePlanResponse_2(
                this,
                Invocation.method(#createMealPlan, [params]),
              ),
            ),
          )
          as _i6.Future<_i4.CreatePlanResponse>);
}

/// A class which mocks [PlanLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlanLocalDataSource extends _i1.Mock
    implements _i5.PlanLocalDataSource {
  MockPlanLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> cacheDashboardData(_i2.DashboardResponse? dashboard) =>
      (super.noSuchMethod(
            Invocation.method(#cacheDashboardData, [dashboard]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cacheWeeklyPlan(_i8.WeeklyPlan? weeklyPlan) =>
      (super.noSuchMethod(
            Invocation.method(#cacheWeeklyPlan, [weeklyPlan]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<_i9.DashboardEntity?> getDashboardStream() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardStream, []),
            returnValue: _i6.Stream<_i9.DashboardEntity?>.empty(),
          )
          as _i6.Stream<_i9.DashboardEntity?>);

  @override
  _i6.Stream<_i10.WeeklyDetailEntity?> getWeeklyPlanStream(int? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklyPlanStream, [groupId]),
            returnValue: _i6.Stream<_i10.WeeklyDetailEntity?>.empty(),
          )
          as _i6.Stream<_i10.WeeklyDetailEntity?>);
}
