// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdSPydl7ek64hGEx4LcL8R8d7vUJSx2yw',
    appId: '1:1021070550729:web:2493b3af73bb004a748f18',
    messagingSenderId: '1021070550729',
    projectId: 'makanapa-475ad',
    authDomain: 'makanapa-475ad.firebaseapp.com',
    storageBucket: 'makanapa-475ad.firebasestorage.app',
    measurementId: 'G-KEMFJTGRJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8SbcXCrHksHsQsV1SYzBeEFSILL5n1Ys',
    appId: '1:1021070550729:android:de4c4a60b9bc40bf748f18',
    messagingSenderId: '1021070550729',
    projectId: 'makanapa-475ad',
    storageBucket: 'makanapa-475ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeUVyxhEnhwEHPuZPboHLhIJQ4lf0VJCg',
    appId: '1:1021070550729:ios:dc62f3c202ac63d7748f18',
    messagingSenderId: '1021070550729',
    projectId: 'makanapa-475ad',
    storageBucket: 'makanapa-475ad.firebasestorage.app',
    androidClientId: '1021070550729-14t73nqhv8vdl7lgm8m5a2dhc92bhf0f.apps.googleusercontent.com',
    iosClientId: '1021070550729-750kq0pmfc8slb5kmb1f6f4ns58qe2up.apps.googleusercontent.com',
    iosBundleId: 'com.app.makanapa',
  );

}