// Mocks generated by Mockito 5.4.6 from annotations
// in makanapa/test/features/shared/main/main_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:makanapa/features/home/domain/models/avaiblity_item.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AvaiblityItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockAvaiblityItem extends _i1.Mock implements _i2.AvaiblityItem {
  MockAvaiblityItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime get startDate =>
      (super.noSuchMethod(
            Invocation.getter(#startDate),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#startDate)),
          )
          as DateTime);

  @override
  DateTime get endDate =>
      (super.noSuchMethod(
            Invocation.getter(#endDate),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#endDate)),
          )
          as DateTime);
}
