-- ============================================================
-- Makan Apa - Database Schema
-- This file contains database structure only (NO DATA)
-- ============================================================

-- Enable required extensions
create extension if not exists pgcrypto with schema extensions;

-- ============================================================
-- TABLES
-- ============================================================

create table public.user_profile (
  uid uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  user_name text not null default ''::text,
  email text not null default ''::text,
  phone_number text null default ''::text,
  avatar text null,
  salt_code text not null default encode(extensions.gen_random_bytes (16), 'hex'::text),
  constraint user_profile_pkey primary key (uid),
  constraint user_profile_email_key unique (email)
) TABLESPACE pg_default;

create table public.faq (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  question text not null,
  answer text not null,
  constraint faq_pkey primary key (id)
) TABLESPACE pg_default;

create table food."Bahan" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null default ''::text,
  type public.bahantype null,
  unit public.unittype null,
  updated_at timestamp with time zone null default now(),
  basket_hidden boolean null default false,
  constraint Bahan_pkey primary key (id)
) TABLESPACE pg_default;


create table food."Resep" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null default ''::text,
  picture text null,
  type public.reseptype not null,
  class public.classtype not null,
  updated_at timestamp with time zone not null default now(),
  image_status public.image_status null default 'pending'::image_status,
  image_generation_error text null,
  steps_link text null,
  is_hidden boolean not null default false,
  en_name text null default ''::text,
  constraint Resep_pkey primary key (id),
  constraint Resep_id_key unique (id)
) TABLESPACE pg_default;

create table food."ResepDetail" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  resep_id bigint null,
  bahan_id bigint null,
  quantity double precision null,
  constraint ResepDetail_pkey primary key (id),
  constraint unique_resep_bahan unique (resep_id, bahan_id),
  constraint ResepDetail_bahan_id_fkey foreign KEY (bahan_id) references food."Bahan" (id) on update CASCADE on delete set null,
  constraint ResepDetail_resep_id_fkey foreign KEY (resep_id) references food."Resep" (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table food."Resep_Bookmark" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null default auth.uid (),
  recipe_id bigint null,
  is_bookmarked boolean not null default true,
  constraint Resep_Bookmark_pkey primary key (id),
  constraint Resep_Bookmark_id_key unique (id),
  constraint Resep_Bookmark_recipe_id_fkey foreign KEY (recipe_id) references food."Resep" (id),
  constraint Resep_Bookmark_user_id_fkey foreign KEY (user_id) references user_profile (uid)
) TABLESPACE pg_default;

create table plan.group (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  start_date timestamp without time zone not null,
  start_timestamp bigint not null,
  end_date timestamp without time zone not null,
  end_timestamp bigint not null,
  user_id uuid not null,
  updated_at timestamp with time zone not null default now(),
  constraint group_pkey primary key (id),
  constraint group_user_id_fkey foreign KEY (user_id) references user_profile (uid) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table plan.meal (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  lunch bigint null,
  dinner bigint null,
  group_id bigint not null,
  dates timestamp without time zone null,
  updated_at timestamp with time zone not null default now(),
  user_id uuid null,
  constraint meal_pkey primary key (id),
  constraint meal_group_id_fkey foreign KEY (group_id) references plan."group" (id) on update CASCADE on delete CASCADE,
  constraint meal_lunch_main_fkey foreign KEY (lunch) references food."Resep" (id) on update CASCADE on delete set null,
  constraint meal_lunch_side_fkey foreign KEY (dinner) references food."Resep" (id) on update CASCADE on delete set null,
  constraint meal_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

CREATE OR REPLACE VIEW plan.meal_details_view 
WITH (security_invoker = true)  
AS
SELECT 
    m.id AS meal_id,
    m.group_id,
    m.dates,
    m.user_id,
    
    -- Lunch Details
    l.id AS lunch_id,
    l.name AS lunch_name,
    l.en_name AS lunch_en_name,
    l.type AS lunch_type,
    l.class AS lunch_class,
    l.picture AS lunch_picture,
    
    -- Dinner Details
    d.id AS dinner_id,
    d.name AS dinner_name,
    d.en_name AS dinner_en_name,
    d.type AS dinner_type,
    d.class AS dinner_class,
    d.picture AS dinner_picture
FROM plan.meal m
LEFT JOIN food."Resep" l ON m.lunch = l.id
LEFT JOIN food."Resep" d ON m.dinner = d.id;

-- Ensure permissions are correct
GRANT SELECT ON plan.meal_details_view TO authenticated;

-- ============================================================
-- INDEXES
-- ============================================================

create index IF not exists trgm_idx_bahan_name_lower on food."Bahan" using gin (lower(name) gin_trgm_ops) TABLESPACE pg_default;
