// Mocks generated by Mockito 5.4.6 from annotations
// in makanapa/test/features/basket/presentation/detail/controllers/basket_detail_bloc_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:makanapa/features/basket/domain/models/basket_group.dart'
    as _i6;
import 'package:makanapa/features/basket/domain/models/basket_option.dart'
    as _i5;
import 'package:makanapa/features/basket/domain/repositories/basket_repository.dart'
    as _i3;
import 'package:makanapa/features/recipe/domain/models/ingredient_enum.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BasketRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBasketRepository extends _i1.Mock implements _i3.BasketRepository {
  MockBasketRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<String, _i5.BasketSummary>> getIngredientsSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getIngredientsSummary, []),
            returnValue:
                _i4.Future<_i2.Either<String, _i5.BasketSummary>>.value(
                  _FakeEither_0<String, _i5.BasketSummary>(
                    this,
                    Invocation.method(#getIngredientsSummary, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<String, _i5.BasketSummary>>);

  @override
  _i4.Stream<_i5.BasketSummary> getIngredientOption() =>
      (super.noSuchMethod(
            Invocation.method(#getIngredientOption, []),
            returnValue: _i4.Stream<_i5.BasketSummary>.empty(),
          )
          as _i4.Stream<_i5.BasketSummary>);

  @override
  _i4.Stream<_i6.BasketGroup> getBasketData({
    required int? groupId,
    required _i7.IngredientEnum? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBasketData, [], {
              #groupId: groupId,
              #type: type,
            }),
            returnValue: _i4.Stream<_i6.BasketGroup>.empty(),
          )
          as _i4.Stream<_i6.BasketGroup>);

  @override
  _i4.Future<_i2.Either<String, void>> getIngridientData({
    required int? groupId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getIngridientData, [], {#groupId: groupId}),
            returnValue: _i4.Future<_i2.Either<String, void>>.value(
              _FakeEither_0<String, void>(
                this,
                Invocation.method(#getIngridientData, [], {#groupId: groupId}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<String, void>>);

  @override
  _i4.Future<_i2.Either<String, void>> updateMark({
    required int? groupId,
    required int? ingredientId,
    required bool? isMarked,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMark, [], {
              #groupId: groupId,
              #ingredientId: ingredientId,
              #isMarked: isMarked,
            }),
            returnValue: _i4.Future<_i2.Either<String, void>>.value(
              _FakeEither_0<String, void>(
                this,
                Invocation.method(#updateMark, [], {
                  #groupId: groupId,
                  #ingredientId: ingredientId,
                  #isMarked: isMarked,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<String, void>>);
}
