// Mocks generated by Mockito 5.4.6 from annotations
// in makanapa/test/features/onboarding/data/repositories/login_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:makanapa/features/onboarding/data/data_source/login/login_data_source.dart'
    as _i4;
import 'package:makanapa/features/onboarding/data/data_source/user/user_data_source.dart'
    as _i7;
import 'package:makanapa/features/onboarding/data/models/entity/user_entity.dart'
    as _i9;
import 'package:makanapa/features/onboarding/data/models/response/auth_data_response.dart'
    as _i2;
import 'package:makanapa/features/onboarding/data/models/response/user_data_response.dart'
    as _i3;
import 'package:makanapa/features/onboarding/domain/models/signup_request.dart'
    as _i6;
import 'package:makanapa/features/onboarding/domain/models/user.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthDataResponse_0 extends _i1.SmartFake
    implements _i2.AuthDataResponse {
  _FakeAuthDataResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserDataResponse_1 extends _i1.SmartFake
    implements _i3.UserDataResponse {
  _FakeUserDataResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRemoteDataSource extends _i1.Mock
    implements _i4.LoginRemoteDataSource {
  MockLoginRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthDataResponse> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i5.Future<_i2.AuthDataResponse>.value(
              _FakeAuthDataResponse_0(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthDataResponse>);

  @override
  _i5.Future<_i2.AuthDataResponse> signInWithGoogle(
    String? idToken,
    String? accessToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, [idToken, accessToken]),
            returnValue: _i5.Future<_i2.AuthDataResponse>.value(
              _FakeAuthDataResponse_0(
                this,
                Invocation.method(#signInWithGoogle, [idToken, accessToken]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthDataResponse>);

  @override
  _i5.Future<_i2.AuthDataResponse> signUpWithEmailAndPassword(
    _i6.SignupRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailAndPassword, [request]),
            returnValue: _i5.Future<_i2.AuthDataResponse>.value(
              _FakeAuthDataResponse_0(
                this,
                Invocation.method(#signUpWithEmailAndPassword, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthDataResponse>);
}

/// A class which mocks [LoginLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginLocalDataSource extends _i1.Mock
    implements _i4.LoginLocalDataSource {
  MockLoginLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> setUserLoginType(String? type) =>
      (super.noSuchMethod(
            Invocation.method(#setUserLoginType, [type]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i7.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.UserDataResponse> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i5.Future<_i3.UserDataResponse>.value(
              _FakeUserDataResponse_1(
                this,
                Invocation.method(#getUser, [userId]),
              ),
            ),
          )
          as _i5.Future<_i3.UserDataResponse>);

  @override
  _i5.Future<_i3.UserDataResponse> createUser(
    _i2.AuthDataResponse? authData, {
    String? userName = 'null',
    String? phoneNumber,
    String? avatar,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createUser,
              [authData],
              {#userName: userName, #phoneNumber: phoneNumber, #avatar: avatar},
            ),
            returnValue: _i5.Future<_i3.UserDataResponse>.value(
              _FakeUserDataResponse_1(
                this,
                Invocation.method(
                  #createUser,
                  [authData],
                  {
                    #userName: userName,
                    #phoneNumber: phoneNumber,
                    #avatar: avatar,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.UserDataResponse>);
}

/// A class which mocks [UserLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDataSource extends _i1.Mock
    implements _i7.UserLocalDataSource {
  MockUserLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveUser(_i8.UserData? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i9.UserEntity?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i9.UserEntity?>.value(),
          )
          as _i5.Future<_i9.UserEntity?>);

  @override
  _i5.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
